# Generated by Django 3.1.5 on 2021-02-16 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210216_2041'),
        ('post', '0004_auto_20210216_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='users.profile'),
        ),
    ]
