# Generated by Django 3.1.5 on 2021-02-17 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210216_2041'),
        ('post', '0005_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='attachments',
            field=models.FileField(default=None, upload_to='files/'),
        ),
    ]
